### PR TITLE
Add support for emails

### PR DESCRIPTION
**Pull request by SamyPesse**
This PR adds "emails" to the profile suing BitBucket API: https://confluence.atlassian.com/display/BITBUCKET/emails+Resource#emailsResource-GETalistofuser'semailaddresses

It has been tested and it used on a project.

### CODE REVIEW

**Comment by SamyPesse** [comment]
@jaredhanson ?

**Comment by fundon** [comment]
Need update to v2 and update API urls.

**Comment by Santinell** [comment]
+1 for merge

**Comment by jaredhanson** [comment]
Equivalent functionality has been implemented and released in v2.0.0.

**Pull request closed without merging**
